# Generated by Django 3.2.13 on 2022-06-18 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeclockapp', '0004_auto_20220618_0603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clock',
            old_name='clockedIn',
            new_name='clockIn',
        ),
        migrations.RenameField(
            model_name='clock',
            old_name='clockedOut',
            new_name='clockOut',
        ),
    ]
