# Generated by Django 3.2.13 on 2022-06-19 08:48

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('timeclockapp', '0005_auto_20220618_0605'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clock',
            new_name='ClockItem',
        ),
    ]
